version: 2
aliases:
  - &GCP-auth
    name: GCP Authenticate
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/gcp_authenticate.sh
  - &docker-login
    name: Docker login
    command: |
      echo 'export GCLOUD_SERVICE_KEY="$GCLOUD_SERVICE_KEY"' >> $BASH_ENV
      /tools/docker_login.sh
  - &docker-build-and-push
    name: Docker build and push
    command: |
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export BUILD_ARGS="--build-arg NEXUS_USER=$NEXUS_USER --build-arg NEXUS_PASS=$NEXUS_PASS"' >> $BASH_ENV
      /tools/docker_build_push.sh
  - &post-hook
    name: Notify about build and docker image pushed
    command: |
      echo 'export CIRCLE_PROJECT_REPONAME="$CIRCLE_PROJECT_REPONAME"' >> $BASH_ENV
      echo 'export CIRCLE_SHA1="$CIRCLE_SHA1"' >> $BASH_ENV
      echo 'export BUILD_STATUS_API_KEY="$BUILD_STATUS_API_KEY"' >> $BASH_ENV
      /tools/build_notify.sh
jobs:
  build:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
      - image: mdillon/postgis:9.6
        environment:
          TZ: Europe/Oslo
          POSTGRES_DB: chouette_test
          POSTGRES_USER: chouette
          POSTGRES_PASSWORD: chouette
    steps:
      - checkout
      - run:
          name: Copy test config file before running tests
          command: |
            cp .circleci/application.yml config/application.yml
      - run:
          name: Install ruby and bundler
          command: |
            apt-get update
            mkdir -p /usr/share/man/man1 /usr/share/man/man7
            apt-get install -y --no-install-recommends ruby2.3 locales
            echo "en_US.UTF-8 UTF-8" > /etc/locale.gen
            locale-gen
            gem2.3 install --no-ri --no-rdoc bundler
      - run:
          name: Install bundler packages
          command: |
            cp Gemfile Gemfile.lock /app/
            apt-get install -y --no-install-recommends build-essential ruby2.3-dev libpq-dev libxml2-dev zlib1g-dev libmagic-dev libmagickwand-dev git-core libpq5 libxml2 zlib1g libmagic1 imagemagick libproj-dev postgresql-client-common postgresql-client-9.6 cron
      - run:
          name: Prepare nodejs 6.x and yarn package installation
          command: |
            apt-get update && apt-get install -y --no-install-recommends curl gnupg ca-certificates apt-transport-https
            curl -sS https://dl.yarnpkg.com/debian/pubkey.gpg | apt-key add -
            echo "deb https://dl.yarnpkg.com/debian/ stable main" > /etc/apt/sources.list.d/yarn.list
            curl -sS https://deb.nodesource.com/gpgkey/nodesource.gpg.key | apt-key add -
            echo "deb https://deb.nodesource.com/node_6.x stretch main" > /etc/apt/sources.list.d/nodesource.list
            apt-get update && apt-get install -y --no-install-recommends yarn nodejs
      - run:
          name: Copy default database config file
          command: cp -r config/database/ci.yml config/database.yml
      - run:
          name: Create locale folder
          command: mkdir -p locales
      - run:
          name: Print some info and versions
          command: |
            set -o xtrace
            ruby -v
            gem list bundler
            bundler -v
      - run:
          name: Bundle install
          command: |
            set -o xtrace
            bundle config build.nokogiri --use-system-libraries --with-xml2-include=/usr/include/libxml2
            bundle install --deployment
      - run:
          name: Rake create and migrate
          command: |
            bundle exec rake db:create
            bundle exec rake db:migrate
      - run:
          name: Rake spec
          command: |
            export RAIL_ENV=test
            bundle exec rake db:reset
            bundle exec rake spec
      - store_test_results:
          path: test_results
  deploy-docker:
    docker:
      - image: eu.gcr.io/carbon-1287/circleci-toolbox-image
        auth:
          username: _json_key
          password: $GCLOUD_SERVICE_KEY
    environment:
      DEBIAN_FRONTEND: "noninteractive"
    steps:
      - checkout
      - setup_remote_docker:
          docker_layer_caching: true
      - run: *GCP-auth
      - run: *docker-login
      - run: *docker-build-and-push
      - run: *post-hook
workflows:
  version: 2
  build_test_deploy:
    jobs:
      - build:
          context: org-carbon
      - deploy-docker:
          context: org-carbon
          requires:
            - build
          filters:
            branches:
              only: entur_develop
